# 인증기능 비활성화
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      # 실제 로그를 저장할 디렉토리
      chunks_directory: /loki/chunks

      # 알림 규칙등의 설정을 저장할 디렉토리
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24

      # 시계열 데이터베이스 형식으로 로그 저장
      store: tsdb

      # 파일 시스템을 오브젝트 스토어로 사용
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# 보관기간 90일 설정
limits_config:
  retention_period: 2160h
  reject_old_samples: true
  reject_old_samples_max_age: 2160h

  # 쿼리 시 캐시 데이터의 최대 유효기간
  max_cache_freshness_per_query: 10m

ruler:
  alertmanager_url: http://localhost:9093