server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: waiting-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/api/v1/users/login, /user-service/api/v1/users/sign-up, /user-service/api/v1/users/reissue
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: spot-service
              uri: lb://spot-service
              predicates:
                - Path=/spot-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/spot-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: reservation-service
              uri: lb://reservation-service
              predicates:
                - Path=/reservation-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservation-service/(?<segment>.*), /$\{segment}